sonata_admin:
    title: 'Game Admin'
    dashboard:
        groups:
            game_management:
                label: "Game Management"
                items:
                    - admin.game
                    - admin.task
            game_statistics:
                label: "Statistics"
                items:
                    - admin.user_game_stats
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
