services:
  database-test:
    container_name: psql_test_db_8_10_game
    image: postgres:17
    environment:
      POSTGRES_USER: ${DOCKER_POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${DOCKER_POSTGRES_DB_TEST}
    ports:
      - '4307:5432'
    volumes:
      - ./postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DOCKER_POSTGRES_USER_TEST} -d ${DOCKER_POSTGRES_DB_TEST}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  database:
    container_name: psql_8_10_game
    image: postgres:17
    environment:
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
    ports:
      - '4306:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DOCKER_POSTGRES_USER} -d ${DOCKER_POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  php:
    container_name: php8_10_game
    build:
      context: .
      dockerfile: php/Dockerfile
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - '8282:80'
    volumes:
      - .:/var/www/10_game
    depends_on:
      database:
        condition: service_healthy
      database-test:
        condition: service_healthy