services:
  database-test:
    container_name: psql_test_db_8_10_game
    image: postgres:17
    environment:
      POSTGRES_USER: ${DOCKER_POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${DOCKER_POSTGRES_DB_TEST}
    ports:
      - '4307:5432'
    volumes:
      - ./postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DOCKER_POSTGRES_USER_TEST} -d ${DOCKER_POSTGRES_DB_TEST}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  database:
    container_name: psql_8_10_game
    image: postgres:17
    environment:
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
    ports:
      - '4306:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DOCKER_POSTGRES_USER} -d ${DOCKER_POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  php:
    container_name: php8_10_game
    build:
      context: ./php
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - '9002:9000'
    volumes:
      - .:/var/www/10_game
    depends_on:
      database:
        condition: service_healthy
      database-test:
        condition: service_healthy

  nginx:
    container_name: nginx3_10_game
    image: nginx:stable-alpine
    ports:
      - '8282:80'
    volumes:
      - .:/var/www/10_game
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

####> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-16}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#      POSTGRES_USER: ${POSTGRES_USER:-app}
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
#      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      # - ./docker/db/data:/var/lib/postgresql/data:rw
####< doctrine/doctrine-bundle ###
#
#volumes:
####> doctrine/doctrine-bundle ###
#  database_data:
####< doctrine/doctrine-bundle ###
