app.swagger_ui:
    path: /api/doc
    methods: GET
    controller: nelmio_api_doc.controller.swagger_ui

app.swagger:
    path: /api/doc.json
    methods: GET
    controller: nelmio_api_doc.controller.swagger